$# LS-DYNA Keyword file created by LS-PrePost(R) 2024/R1(4.11)-30Jan2024
$# Created on Jun-9-2025 (08:29:54)
*KEYWORD   
*NODE
$#   nid               x               y               z      tc      rc
       1          0.0000             0.0             0.0       0       0
       2          0.0127             0.0           0.002       0       0
       3          0.0127             0.0           0.004       0       0
       4          0.0127             0.0           0.006       0       0
*PART
$#                                                                         title
New part from tetrahedron mesher
$#     pid     secid       mid     eosid      hgid      grav    adpopt      tmid
         1         0         0         0         0         0         0         0
*ELEMENT_SOLID
$#   eid     pid      n1      n2      n3      
       1       1       1       2       3       4       4       4       4       4
*END
